use_frameworks!

platform :ios, '10.0'

target 'YoungminSampleSDK_Example' do
  pod 'YoungminSampleSDK', :path => '../'

  target 'YoungminSampleSDK_Tests' do
    inherit! :search_paths

    
  end
end
